ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    baudrate: 128000

    lidar_type: 1
    device_type: 0
    sample_rate: 5
    abnormal_check_count: 4

    # ===== MOTOR CONTROL =====
    support_motor_dtr: false

    # ===== SAFE BASELINE =====
    fixed_resolution: false
    reversion: false
    inverted: false
    auto_reconnect: true
    isSingleChannel: true
    intensity: false

    angle_min: -180.0
    angle_max: 180.0
    range_min: 0.12
    range_max: 10.0

    frequency: 5.0
    invalid_range_is_inf: false

